giraffe-fsharp/Giraffe

- samples/AspNetCore.Lambda.SampleApp/Program.fs
Just a preference thing, a little for F# idiomatic IMO
> Use functions rather than classes in sample app

- src/AspNetCore.Lambda/AspNetCore.Lambda.fsproj
> Support for netstandard1.3

- README.md
- samples/SampleApp/SampleApp/Html.fs
- samples/SampleApp/SampleApp/Program.fs
- samples/SampleApp/SampleApp/SampleApp.fsproj
- src/Giraffe/Giraffe.fsproj
- src/Giraffe/Html.fs
- src/Giraffe/HttpHandlers.fs
- tests/Giraffe.Tests/Giraffe.Tests.fsproj
- tests/Giraffe.Tests/HtmlTests.fs
- tests/Giraffe.Tests/HttpHandlerTests.fs
As discussed in https://github.com/dustinmoris/Giraffe/issues/32, the port of Suave experimental Html.
I've added a sample, unit test and updated the README.
Let me know if anything is missing.
Cheers!
> Initial attempt for Html Nodes

- README.md
> fix copy paste error in readme (webApp)

- src/Giraffe/HttpContextExtensions.fs
- tests/Giraffe.Tests/ModelBindingTests.fs
> Add Option<'T> support for BindQueryString

- README.md
Sorry I forgot to add this to #58 .  Anything else I'm forgetting?
> Add linux builds to readme

- Giraffe.sln
- build.sh
- samples/SampleApp/SampleApp/SampleApp.fsproj
- src/Giraffe.DotLiquid/Giraffe.DotLiquid.fsproj
- src/Giraffe.DotLiquid/HttpHandlers.fs
- src/Giraffe.Razor/Giraffe.Razor.fsproj
- src/Giraffe.Razor/HttpHandlers.fs
- src/Giraffe.Razor/Middleware.fs
- src/Giraffe.Razor/RazorEngine.fs
- src/Giraffe/HttpHandlers.fs
- src/Giraffe/Middleware.fs
- tests/Giraffe.Tests/Giraffe.Tests.fsproj
> Separate projects for View Engines

- src/Giraffe/HttpContextExtensions.fs
Just an extension I've found useful in my code
> TryGetQueryStringValue

- template/content/Program.fs
Hi, spotted a small mistake in the dotnet template code
> Fixed incorrect code in dotnet template

- src/Giraffe/Giraffe.fsproj
- src/Giraffe/HttpHandlers.fs
- tests/Giraffe.Tests/HttpHandlerTests.fs
Something else I've been using in my own project. It converts a route with parameters
`/test/{foo}/{bar}`
into a `Map<string, string>` so you can then read the parameters in your route handler. I've also implemented the `?` operator for ease
`fun map -> sprintf "%s %s" map?foo map?bar |> text`
> Implement routeMap

- template/content/Program.fs
- template/content/_AppName.fsproj
Considering Azure/IIS Deployment Scenarios. #44 I updated the template to support those scenarios out of the box
> Added IIS Packages for Azure Deployment

- samples/IdentityApp/IdentityApp/IdentityApp.fsproj
- samples/IdentityApp/IdentityApp/Program.fs
- template/content/Program.fs
- template/content/_AppName.fsproj
Demonstrates how to enable the CORS mechanism in ASP.NET Core.
> Configuring CORS.

- README.md
fix doubling of word: "be be" -> "be"
> fix doubling of word

- README.md
- samples/SampleApp/SampleApp/Program.fs
- src/Giraffe/HttpHandlers.fs
> Lightweight policy based authorization

- tests/Giraffe.Tests/AuthHandlerTests.fs
- tests/Giraffe.Tests/Giraffe.Tests.fsproj
> Authorization tests added; FsCheck included in project

- README.md
- src/Giraffe/HttpHandlers.fs
- src/Giraffe/TokenRouter.fs
- tests/Giraffe.Tests/TokenRouterTests.fs
To be more consistent and not need choose have added method filter routing functions.
Have also fixed a bug for fringe case not identified before.
> TokenRouter Urgent Bug Fix & Added Method Filtering to TokenRouter 

- src/Giraffe/Giraffe.fsproj
- src/Giraffe/HttpStatus.fs
> Porting most HTTP Status helpers from suave

- src/Giraffe/Common.fs
- src/Giraffe/GiraffeViewEngine.fs
- src/Giraffe/HttpContextExtensions.fs
- src/Giraffe/HttpHandlers.fs
- src/Giraffe/Middleware.fs
we should be careful with /// comments. They are used as XML docs. Weird things happen:
> Make XML doc comments normal comments

- src/Giraffe/GiraffeViewEngine.fs
Added blockquote tag, integrity attribute (link/script), scoped tag (style)
> +blockquote +_integrity +_scoped

- src/Giraffe/Auth.fs
- src/Giraffe/Core.fs
- src/Giraffe/Giraffe.fsproj
Address #224. It's working in another project, but the code could be polished further.
I'll need help with creating tests for it because of the dependency injection of `IAuthorizationService`.
> WIP: Policy-based authorization

- src/Giraffe/Routing.fs
- tests/Giraffe.Tests/RoutingTests.fs
Fixes #338 
Not sure about the naming convention for unit tests
> Fix nested subRouteCi case sensitivity

- DOCUMENTATION.md
I updated the verbiage and the example. Feel free to edit to your liking.
> Added FSharpLu to doc example

- src/Giraffe/Common.fs
- tests/Giraffe.Tests/DateTimeTests.fs
- tests/Giraffe.Tests/Giraffe.Tests.fsproj
New ToIsoString methods to resolve issue #367 around wrong date string being produced.
> Adding ToIsoString method and unit tests

- RELEASE_NOTES.md
- src/Giraffe/FormatExpressions.fs
- src/Giraffe/Routing.fs
- tests/Giraffe.Tests/FormatExpressionTests.fs
- tests/Giraffe.Tests/RoutingTests.fs
Added support for regular expression match mode
Added two extra routing extensions which are using it
Added some basic tests
Addresses #341
This is draft, comments are welcome
Edit: after looking at it for a while, I am pleased with the current state of pr, or I lost the ability for self-criticism
> routeStartsWithf + routeStartsWithCif

- DOCUMENTATION.md
Updating documentation to align with change I introduced several months ago in #372. 
I know code PRs should be opened against dev but since this is just a documentation change I thought master would be fine? Let me know if not and I can open against the dev branch.
> Updating documentation to align with previous code change.

- src/Giraffe/Giraffe.fsproj
In reviewing #389, I've determined some of the dependencies could be removed, and have targeted the `deveop` branch. I've add you @isaacabraham as co-author.
> Tidy up references

- src/Giraffe/Core.fs
As mentioned in #483 it would be nice to have a functional wrapper around `ctx.SetContentType` similar to `setStatusCode`.
> Add setContentType function.

- .github/workflows/build.yml
- samples/EndpointRoutingApp/EndpointRoutingApp/EndpointRoutingApp.fsproj
- src/Giraffe/Giraffe.fsproj
- tests/Giraffe.Tests/Giraffe.Tests.fsproj
Changes:
- Target .NET 7
- Updated various dependencies
addresses https://github.com/giraffe-fsharp/Giraffe/issues/526
> Upgrade to .NET 7

- README.md
Video link: https://www.youtube.com/watch?v=yDBpd07SdHE
> [Documentation] Add another tutorial video to README

- .github/workflows/build.yml
- src/Giraffe/Giraffe.fsproj
- tests/Giraffe.Tests/Giraffe.Tests.fsproj
This restores TFM 6.0 because we should support it as best we can.
> Restore 6.0 as tfm

- DOCUMENTATION.md
With this PR, I'm fixing the example snippets for the functions `WriteStreamAsync` and `WriteFileStreamAsync`.
The test instructions are detailed in the issue related to this PR, which is presented in the next section.
- Close https://github.com/giraffe-fsharp/Giraffe/issues/530
> Fix documentation snippet for `WriteStreamAsync` and `WriteFileStreamAsync`

- src/Giraffe/ModelParser.fs
Another tiny performance optimization: reuse the same RegEx
> No need to build so many Regex

- .github/workflows/build.yml
With this PR, I'm:
* Updating the actions version, to use the most up to date, leveraging their optimizations;
* Adding a concurrency configuration to kill old jobs when new commits are sent to the PR
> Improve CI by updating actions version and avoid concurrent jobs for the same PR

- .github/workflows/publish.yml
Fix the pre-release CI workflow due to the [actions/download-artifact@v4](https://github.com/actions/download-artifact).
> Hotfix pre-release workflow

- DEVGUIDE.md
With this PR, I'm improving the DEVGUIDE documentation with a SemVer observation from @TheAngryByrd and @baronfel [link](https://github.com/giraffe-fsharp/Giraffe/pull/596#issuecomment-2111097042).
> Improve DEVGUIDE with SemVer pre-release observation

- DOCUMENTATION.md
- README.md
- RELEASE_NOTES.md
With this PR, I'm tackling the points raised at issue https://github.com/giraffe-fsharp/Giraffe/issues/606, on how to improve release notes regarding breaking changes.
- https://github.com/giraffe-fsharp/Giraffe/issues/606
> Update RELEASE NOTES (breaking changes), README (link to release notes) and DOCUMENTATION

- .vscode/launch.json
- .vscode/tasks.json
With this PR I'm updating the `.vscode` samples debug configuration to use current sample projects.
Try it on VS Code debug tool.
- Close https://github.com/giraffe-fsharp/Giraffe/issues/592
> Update `.vscode` samples debug configuration

- Giraffe.sln
- samples/GlobalRateLimiting/GlobalRateLimiting.fsproj
- samples/GlobalRateLimiting/Program.fs
- samples/GlobalRateLimiting/README.md
- samples/GlobalRateLimiting/global-rate-limiting-test.fsx
With this PR, I'm:
* Adding a global rate limiting sample;
Instructions are available at sample's README.
- Related to https://github.com/giraffe-fsharp/Giraffe/issues/618.
> Add global rate limiting sample

- .config/dotnet-tools.json
- src/Giraffe/Giraffe.fsproj
refs https://github.com/giraffe-fsharp/Giraffe/pull/660#issuecomment-2971457757 - update the analyzer packages and the analyzers cli tool in  one go to keep the versions in step
> Update fsharp-analyzers and the analyzer packages
