src/AspNetCore.Lambda/FormatExpressions.fs
When running the code on a non English operating system the numbers (especially doubles) are parsed in the wrong format.
This can be solved by using the F#'s own conversion functions which are culture invariant.
=> Use culture invariant parse functions

src/Giraffe/ModelBinding.fs
This fixes failing unit tests for  bindQueryString and bindForm on non English OS.
=> Use culture invariant convert function

src/Giraffe/Giraffe.fsproj
Changing the target frameworks did the trick for #46 .
Not sure what will happen on the CI server.
Also creating an old school `fsproj ` console app and getting AspNetCore in general to work on it is a pain.
Some issues I came across:
- Libuv was not copied, see https://github.com/aspnet/KestrelHttpServer/issues/1652
- System.Numerics.Vectors gave a strange assemblyRedirect problem, I had to change my fsproj to
```xml
<Reference Include="System.Numerics.Vectors">
<HintPath>..\packages\System.Numerics.Vectors.4.3.0\lib\net46\System.Numerics.Vectors.dll</HintPath>
<Private>True</Private>
</Reference>
```
See https://github.com/dotnet/corefx/issues/3103
And a redirect in app.config
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
<startup>
<supportedRuntime version="v4.0" …
```
=> Add support for full .NET framework

README.md, samples/SampleApp/SampleApp/Program.fs, src/Giraffe.DotLiquid/HttpHandlers.fs, src/Giraffe.Razor/HttpHandlers.fs, src/Giraffe/HttpHandlers.fs, src/Giraffe/Middleware.fs, tests/Giraffe.Tests/HttpContextExtensionsTests.fs, tests/Giraffe.Tests/HttpHandlerTests.fs
As discussed, PR is using existing async format (not Task), and is just updating Httphandlers to double parameter format that includes continuation.
=> Change to Continuation format

README.md, samples/SampleApp/SampleApp.Tests/Tests.fs, samples/SampleApp/SampleApp/Program.fs, src/Giraffe.DotLiquid/HttpHandlers.fs, src/Giraffe.Razor/HttpHandlers.fs, src/Giraffe.Razor/RazorEngine.fs, src/Giraffe/Common.fs, src/Giraffe/Giraffe.fsproj, src/Giraffe/HttpContextExtensions.fs, src/Giraffe/HttpHandlers.fs, src/Giraffe/Middleware.fs, src/Giraffe/Tasks.fs, tests/Giraffe.Tests/HttpContextExtensionsTests.fs, tests/Giraffe.Tests/HttpHandlerTests.fs
As discussed in issue #53, I have updated new continuation format to use task {} rather than async {}.
This version allows binding to both `Task<'T>` & plain `Task` without the need of type assertions thanks to [TaskBuilder](https://github.com/rspeele/TaskBuilder.fs) based on @rspeele implementation that uses Extention methods & task-like member constraints for seamless overloading. I have emailed Robert and he is happy for us to use in Giraffe based on his implementation (I have removed taskbuilder context-sensitive related code given asp.net core does no context switching and is purely context-insensitive).
This TaskBuilder approach should also allow the use of ValueTask<'T> in the future to remove scheduling of final pipeline completion Tasks of Some/None but for now, Task should be …
=> Task/Task<'T> Computation expression async bindings

src/Giraffe/Tasks.fs
I have added basic async bind overload to `task {}` so people can use async methods in the task builder.
I have also added a basic test that binds to `Async.sleep` to confirm async bind working
=> add async bind overload

.travis.yml, global.json, samples/IdentityApp/IdentityApp/IdentityApp.fsproj, samples/SampleApp/SampleApp.Tests/SampleApp.Tests.fsproj, samples/SampleApp/SampleApp/Program.fs, samples/SampleApp/SampleApp/SampleApp.fsproj, src/Giraffe.DotLiquid/Giraffe.DotLiquid.fsproj, src/Giraffe.Razor/Giraffe.Razor.fsproj, src/Giraffe/Common.fs, src/Giraffe/Giraffe.fsproj, src/Giraffe/HttpContextExtensions.fs, src/Giraffe/HttpHandlers.fs, template/content/_AppName.fsproj, template/giraffe-template.nuspec, tests/Giraffe.Tests/Giraffe.Tests.fsproj, tests/Giraffe.Tests/testerrors
Net 461 should be able to be added as an additional target. `Net46` won't be compatible because of the new AspNetCore compatibility breakage, but `Net461` should work fine.
#76
=> Net(standard|core)2.0

src/Giraffe/Common.fs
readFileAsString was disposing of the stream and the reader before the task completed. This PR fixes that by wrapping the whole thing in a Task CE. (See issue #88)
=> Fix readFileAsString disposing of resources before completion.

samples/IdentityApp/IdentityApp/Program.fs
The CSS property `display` has no value `inline-box`. I think you meant `inline-block`.
=> Fixed some typos in an example page

README.md, src/Giraffe/Giraffe.fsproj, src/Giraffe/TokenParsers.fs, src/Giraffe/TokenRouter.fs, tests/Giraffe.Tests/Giraffe.Tests.fsproj, tests/Giraffe.Tests/TokenRouterTests.fs
Continuing from the previous PR I closed due to metadata being messed with, please see updates in line with updates requested, happy to go over any last bits. 
I separated the routers parsers out into a separate file to reduce clutter.
I amended `blah blah` test to what I expect and now passing but let me know if the url encoding inside unit testing is an issue.
=> TokenRouter

README.md, src/Giraffe/HttpContextExtensions.fs
Added 3 common extension methods to context for writing json, xml & text so that users can do nested writes instead of using pipeline functions. #113
=> Added Nested Response Writing Methods

samples/IdentityApp/IdentityApp/Program.fs, samples/JwtApp/JwtApp/Program.fs, samples/SampleApp/SampleApp/Program.fs, src/Giraffe/Middleware.fs
UseGiraffeErrorHandler ApplicationBuilder extension modified (ignore removed) to support chaining since it should probably never be the last middleware in the pipeline.
```fsharp
app.UseCors(configureCors)
.UseGiraffeErrorHandler(errorHandler)
.UseAuthentication()
.UseGiraffe webApp
```
vs
```fsharp
app.UseCors configureCors |> ignore
app.UseGiraffeErrorHandler errorHandler
app.UseAuthentication() |> ignore
app.UseGiraffe webApp
```
=> UseGiraffeErrorHandler chaining support

template/content/_AppName.fsproj
Fix problem with the template using outdated Giraffe version 0.1.0-beta-110 and nonexistent Giraffe.Razor version 0.1.0-beta-200
=> Fix template referencing wrong packages

src/Giraffe/HttpHandlers.fs, tests/Giraffe.Tests/HttpHandlerTests.fs
Regex generation only worked for paths that started and ended with tokens (/{foo}/{bar}/{id} and not for paths /api/{foo}/{bar}/{id}.
=> Modified regex generation so that tokens are identified at the end of the request path.

src/Giraffe/Common.fs, tests/Giraffe.Tests/HttpHandlerTests.fs, tests/Giraffe.Tests/TokenRouterTests.fs
Returned JSON should be camel-cased as this is the standard format and what is expected.
=> Use camel-case for property values returned as JSON

src/Giraffe/FormatExpressions.fs, src/Giraffe/HttpContextExtensions.fs, src/Giraffe/HttpHandlers.fs, src/Giraffe/TokenRouter.fs
This is urgent fix needed as users reporting routef handler not inferring types correctly and defaulting to obj when uncertain. there is a bug in StringFormat<_,'T> but changing to PrintfFormat<_,_,_,_,'T> gets rid of this inference bug
=> fix StringFormat to PrintfFormat as bug in type inference

samples/IdentityApp/IdentityApp/Program.fs
Cors service is not properly enabled without the the parens. This fixes this error: Unhandled Exception: System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Cors.Infrastructure.ICorsService' while attempting to activate 'Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware'.
=> Fix Unable to resolve Cors service Error

src/Giraffe/XmlViewEngine.fs
According to mdn,the `base` tag is an empty one.
See https://developer.mozilla.org/nl/docs/Web/HTML/Element/base
=> Changed base tag to voidTag

src/Giraffe/HttpContextExtensions.fs, tests/Giraffe.Tests/HttpContextExtensionsTests.fs
This allows users to pass a `CultureInfo` into the BindXXX methods, which allows users to control the de-serialization of the strings. This is particularly useful for DateTimes, for example MM/dd/yyyy vs dd/MM/yyy
There are no API changes and this is opt in using optional parameters. 
let entraderTradeHandler : HttpHandler = 
fun (next:HttpFunc) (ctx:HttpContext) ->  
task {
let config = ctx.GetService<StodDataService.Configuration>()
let query = ctx.BindQueryString<DataServices.EnTrader.TradeQuery>(CultureInfo.CurrentCulture)
use client = DataServices.EnTrader.createService config.EnTraderUrl config.EnTraderUsername config.EnTraderPassword
let! data = DataServices.EnTrader.getTrades query client |> Async.StartAsTask
match data with 
| Ok data -> 
do setData data ctx
return! next ctx
| …
=> Adds the ability to pass a CultureInfo into the BindXXX Methods

src/Giraffe/FormatExpressions.fs, src/Giraffe/HttpHandlers.fs, src/Giraffe/TokenRouter.fs, tests/Giraffe.Tests/HttpHandlerTests.fs
To address an issue a number of users are having eg #184 , this validation will run at startup and warn the user of any invalid parse matching rather than it just failing to match at runtime for no apparent reason.
Test also added to cover common case of '%d' being expected to be a `int` rather than `int64`
@forki @isaacabraham
=> added parseValidate

build.ps1, samples/SampleApp/SampleApp.Tests/SampleApp.Tests.fsproj, tests/Giraffe.Tests/Giraffe.Tests.fsproj
Closes #190. This is the 1st pass at using `dotnet-xunit` to run the tests for Giraffe.Tests.fsproj.  I'm not a powershell expert so please criticize.   
Due to some weird behavior in dotnet's cli tooling (https://github.com/xunit/xunit/issues/1573 and https://github.com/dotnet/cli/issues/7901#issuecomment-352009367) we have to pass the `-fxversion` to `dotnet-xunit`.  
```
dotnet xunit -fxversion 2.0.3
Detecting target frameworks in Giraffe.Tests.fsproj...
Building for framework net461...
Giraffe -> /Users/username/Documents/GitHub/Giraffe/src/Giraffe/bin/Debug/net461/Giraffe.dll
Giraffe.Tests -> /Users/username/Documents/GitHub/Giraffe/tests/Giraffe.Tests/bin/Debug/net461/Giraffe.Tests.dll
Running desktop CLR tests for framework net461...
xUnit.net Console Runner (64-bit Desktop .NET …
```
=> WIP: use dotnet-xunit to run *.Tests.fsproj.  Allows for running on mono.

src/Giraffe/Common.fs
Use StreamReader(String) in readFileAsStringAsync, eliminating the need to explicitly initialize a FileStream
- addresses https://github.com/giraffe-fsharp/Giraffe/issues/215
=> Use StreamReader(String) in readFileAsStringAsync

src/Giraffe/ModelBinding.fs
This would fix #279.
Rationale: the PATCH method ([RFC 5789](https://tools.ietf.org/html/rfc5789)) is designed for partial updates, which can be useful in a number of scenarios. It typically carries a body that is structured in some format defined by the Web application: a perfect fit for BindModelAsync. And as #279 and https://github.com/SaturnFramework/Saturn/issues/80 demonstrate, there's at least one real-world use case that could use this feature.
Furthermore, the implementation is trivial, as you can see from this PR. :-)
=> Make BindModelAsync also work on HTTP PATCH requests

src/Giraffe/ModelBinding.fs
Fix for
https://github.com/giraffe-fsharp/Giraffe/issues/287
=> Enabled BindModelAsync<'T> for DELETE HTTP method

samples/SampleApp/SampleApp.Tests/Tests.fs, samples/SampleApp/SampleApp/Program.fs, src/Giraffe/FormatExpressions.fs
a%2Fb%2Bc.d%2Ce 
gives 
a/b c.d,e 
and should gives 
a/b+c.d,e #254
=> SampleApp showing not proper url decoded string. 

README.md
@dustinmoris I added two references in the readme.md file to 2 blogposts I wrote about Giraffe.
- A blogpost about using appsettings.json in a Giraffe web app
- A blogpost about integrating Azure AD in a Giraffe web app. This post also provides more info for #263
=> added community blog post examples in readme

src/Giraffe/ResponseWriters.fs
This is one file micro tuning pr based on results of the continuous run of techempower [tests ](https://www.techempower.com/benchmarks/#section=test&runid=a1843d12-6091-4780-92a6-a747fab77cb1&hw=ph&test=plaintext&p=zik0zj-zik0zj-zijocf-5m9r)
There are 330_000 requests per second difference for this kind of benchmark between the utf8 encoding on each call vs utf8 encoding once in the constructor.
So I've moved utf8 encoding out of HTTP handlers where applicable.
I have not found a way to do the same thing for json because current serializer depends on an instance resolved from HTTP context
=> Micro tuning of response writers

DOCUMENTATION.md, samples/GoogleAuthApp/GoogleAuthApp/Program.fs, samples/IdentityApp/IdentityApp/Program.fs, src/Giraffe/GiraffeViewEngine.fs
Documentation changes for #315 
Funnily enough, (not in this commit) added encoded cases to `HtmlUtf8Benchmark`, and the default one became 3% faster than the original Default.
=> Replaced rawText with encodedText in samples + comments in GiraffeViewEngine

build.sh
This PR resolves issue #321.
Tried running the build script on macOS, got the following error:
```
Failed to execute process './build.sh'. Reason:
exec: Exec format error
The file './build.sh' is marked as an executable but could not be run by the operating system.
```
Looked at the script and saw there was no shebang, so I added the default `#!/bin/sh`.
Ran `$ shellcheck build.sh` and got:
```
export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
^-- SC2155: Declare and assign separately to avoid masking return values.
^-- SC2046: Quote this to prevent word splitting.
```
So I fixed those errors. Now if `pwsh` isn't in the user's `$PATH`, the command will helpfully inform them.
=> Add shebang and fix shellcheck warnings

.psscripts/build-functions.ps1, .travis.yml, DOCUMENTATION.md, RELEASE_NOTES.md, src/Giraffe/Auth.fs, src/Giraffe/Common.fs, src/Giraffe/ComputationExpressions.fs, src/Giraffe/Core.fs, src/Giraffe/FormatExpressions.fs, src/Giraffe/Middleware.fs, src/Giraffe/ModelBinding.fs, src/Giraffe/ModelValidation.fs, src/Giraffe/Negotiation.fs, src/Giraffe/Preconditional.fs, src/Giraffe/ResponseCaching.fs, src/Giraffe/ResponseWriters.fs, src/Giraffe/Routing.fs, src/Giraffe/Streaming.fs
As discussed in #329,  this PR adds asynchronous counter parts for `handleContext` and `handleRequest` along with their docs and release notes. 
```fs
let echoContents (request: HttpRequest) = 
task {
use reader = new StreamReader(request.Body)
let! contents = reader.ReadToEndAsync()
return text contents 
}
let webApp = POST >=> route "/echo" >=> handleRequestAsync echoContents
```
=> Add handleContextAsync and handleRequestAsync with docs

RELEASE_NOTES.md, src/Giraffe/Giraffe.fsproj
Fixes #350
I am struggling to use Giraffe with Azure Functions, and there appears to be no downside to this. It appears that aspnetcore mvc indirectly targets 11.0.2, like azure functions and a lot of Microsoft packages.
We could target 9.x, however it feels appropriate to target 11.x as that is the earliest version to support netstandard2.0, and 11.0.2 has an F# relevant fix: "Fix - Fixed serializing F# enums".
I'm hoping we can get this into a 4.0.0 release?
=> Lower Json.NET version requirement to 11.0.2

RELEASE_NOTES.md, src/Giraffe/ModelBinding.fs, tests/Giraffe.Tests/ModelBindingTests.fs
Support array of 'T as a child in form binding. This PR addresses #349 issue[1].
[1]: After this PR got merged, I'll work on adding support of `seq` and `List` as a child in form binding.
=> Support array of generic type as a child in form binding

src/Giraffe/FormatExpressions.fs, src/Giraffe/Giraffe.fsproj, tests/Giraffe.Benchmarks/Giraffe.Benchmarks.fsproj, tests/Giraffe.Tests/Giraffe.Tests.fsproj
=> More support for netcoreapp3.0

DOCUMENTATION.md, RELEASE_NOTES.md, src/Giraffe/Giraffe.fsproj
I'm proposing to release a new version of Giraffe with these fewer dependencies which are not required for netcore3.0 anymore and which cause some Paket issues for users according to Isaac Abraham who maintains the SAFE stack.
Any objections?
=> Reduced Dependencies

.psscripts/build-functions.ps1, DOCUMENTATION.md, appveyor.yml, global.json, src/Giraffe/Giraffe.fsproj, src/Giraffe/Serialization.fs, tests/Giraffe.Tests/Giraffe.Tests.fsproj, tests/Giraffe.Tests/Helpers.fs, tests/Giraffe.Tests/HttpContextExtensionsTests.fs, tests/Giraffe.Tests/ModelBindingTests.fs
- Updated SDK to 3.1.300
- Switched to just `netcoreapp3.1`
- Removed mono references from build pwsh scripts
- Added System.Text.Json serializer
=> Add System.Text.Json Support

README.md
Current sample code does not build on latest SDK (see below). Here is updated version.
```
dotnet build
Microsoft (R) Build Engine version 16.8.0+126527ff1 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
Determining projects to restore...
Restored Credo.fsproj (in 319 ms).
Program.fs(19,32): warning FS0044: This construct is deprecated. This type is obsolete and will be removed in a future version. The recommended alternative is Microsoft.Extensions.Hosting.IHostEnvironment. [Credo.fsproj]
Program.fs(20,42): error FS0039: The type 'ILoggerFactory' is not defined. [Credo.fsproj]
Program.fs(19,32): warning FS0044: This construct is deprecated. This type is obsolete and will be removed in a future version. The recommended alternative is …
```
=> Update README.md - Sample code

DOCUMENTATION.md
Seems like your forgot to update all references and it looks a bit confusing for newcomers like me
=> Fix old TaskBuilder namespace reference in docs

README.md
My blog has been updated. It runs on jekyll instead of ghost. The urls are changed. To make sure you don't have dead links, I've made this update.
=> updated blog url

src/Giraffe/Giraffe.fsproj, src/Giraffe/Helpers.fs, src/Giraffe/Json.fs, src/Giraffe/Middleware.fs, src/Giraffe/Xml.fs
- Made use of `RecyclableMemoryStreamManager` in XML serialization too
- Added an upper bound (<3.0) to Microsoft.IO.RecyclableMemoryStream because v2 [does not contain breaking changes that are really relevant here](https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream/blob/master/CHANGES.md)
- Wired up `RecyclableMemoryStreamManager` through DI so that users can provide their own fine-tuned instance of the manager
=> Improve RecyclableMemoryStream usage

DOCUMENTATION.md
Operator `=>` got removed but it's still being used in a code sample in the docs
=> Fix endpoint routing docs

.github/workflows/build.yml
Fixes [513](https://github.com/giraffe-fsharp/Giraffe/issues/513) and should unblock builds.
This change alters the versioning used by github actions for builds by utilizing the Github Run Identifier as an "Additional Label" (in semver parlance) rather than a major version number.
Example (from [this failed build](https://github.com/giraffe-fsharp/Giraffe/runs/7060792905?check_suite_focus=true))
* Before: `2564178360` _(`System.ArgumentException: PackageVersion string specified '2564178360' is invalid.`)_
* After: `6.0.0-build.2564178360`
This matches the semver logic: `Example: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0.` (ref: https://semver.org/)
=> Updating github workflow file to use nuget-acceptable version numbers for packaging

src/Giraffe/Helpers.fs
Keep seeing this in Intellisense when it's the one in my codebase I want to use.
=> Make recyclableMemoryStreamManager internal

src/Giraffe/Helpers.fs, src/Giraffe/HttpContextExtensions.fs, tests/Giraffe.Tests/HttpContextExtensionsTests.fs
=> RFC-compliant Content-Length handling for 1xx, 204 and 205 responses and CONNECT requests

src/Giraffe/HttpContextExtensions.fs
Fix spelling in documentation for BindJsonAsync and  BindXmlAsync
=> Fix spelling in docs for BindJsonAsync and  BindXmlAsync

DOCUMENTATION.md, src/Giraffe/Giraffe.fsproj, src/Giraffe/Json.fs, tests/Giraffe.Tests/Helpers.fs
...because the project is [no longer supported](https://github.com/neuecc/Utf8Json/). #451
=> remove Utf8Json support

DOCUMENTATION.md, src/Giraffe/HttpContextExtensions.fs, src/Giraffe/Streaming.fs
With this PR, I'm adding a new function named `GetWebHostEnvironment` to be used instead of the `GetHostingEnvironment`, that is going to be deprecated in the future.
I have updated both the documentation and the codebase itself to use this new function.
Assert that you can build the project.
Run the automated tests:
```bash
cd tests/Giraffe.Tests/
dotnet test
```
- Close https://github.com/giraffe-fsharp/Giraffe/issues/524.
=> Add `GetWebHostEnvironment` function and add deprecation warning to `GetHostingEnvironment`

src/Giraffe/Routing.fs
This is a tiny PR to make the route-check a tiny bit faster by not doing dictionary lookup twice.
=> Minor code optimisation

DOCUMENTATION.md
With this PR I'm removing some empty spaces from the documentation and adding explicitly the statement that the usage of `Giraffe.EndpointRouting` is recommended.
* Close https://github.com/giraffe-fsharp/Giraffe/issues/534
=> Add explicitly the statement that the usage of `Giraffe.EndpointRouting` is recommended

.github/workflows/build.yml, RELEASE_NOTES.md, samples/EndpointRoutingApp/EndpointRoutingApp.fsproj, src/Giraffe/Giraffe.fsproj, src/Giraffe/Xml.fs, tests/Giraffe.Tests/Giraffe.Tests.fsproj, tests/Giraffe.Tests/Helpers.fs, tests/Giraffe.Tests/HttpContextExtensionsTests.fs
Add .net 8 and upgrade dependencies.
Add upgrade dependencies of #566
Building the solution, running tests, and running the sample endpoint app
Close #570
Close #565
=> Update to .net 8

.config/dotnet-tools.json, .github/workflows/fantomas-check.yml, samples/EndpointRoutingApp/Program.fs
With this PR, I'm adding fantomas as a dotnet tool and a new CI workflow to use it to check the samples. I'm also updating the EndpointRoutingApp sample to be fantomas compliant.
Check CI.
- Related to https://github.com/giraffe-fsharp/Giraffe/issues/581
=> Add Fantomas validation to CI

src/Giraffe/EndpointRouting.fs, tests/Giraffe.Tests/EndpointRoutingTests.fs, tests/Giraffe.Tests/Giraffe.Tests.fsproj
With this PR, I'm fixing the EndpointRouting Guid regex ([route constraint](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-8.0#route-constraints)) and adding more automated tests to assert that it's working.
You can use this project example:
```fsharp
open System
open Microsoft.AspNetCore.Builder
open Microsoft.Extensions.DependencyInjection
open Microsoft.Extensions.Hosting
open Giraffe
open Giraffe.EndpointRouting
let endpoints =
[ GET
[ route "/" (text "Hello World")
routef "/try-a-guid/%O" (fun (guid: Guid) -> text $"Success: {guid}") ] ]
let notFoundHandler = "Not Found" |> text |> RequestErrors.notFound
let configureApp (appBuilder: IApplicationBuilder) =
appBuilder.UseRouting().UseGiraffe(endpoints).UseGiraffe(notFoundHandler)
let …
```
=> Fix EndpointRouting Guid regex + tests

.github/workflows/publish.yml
Although the `prerelease` workflow was running with the latest PR changes, it was still not creating the new nuget version, since it was not running the [dotnet nuget push](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push) command.
After realizing this problem, I figured out that in this case it would be better to use the `deploy` workflow that does the job correctly. This way, I'm proposing the removal of `prerelease` workflow and the usage of `deploy` for both `pre-release`s and `release`s on GitHub.
Please let me know what you think.
Check this CI execution: [link](https://github.com/giraffe-fsharp/Giraffe/actions/runs/9070910047/job/24923641652?pr=596).
Notice that the "new" pre-release version was created and it's available on …
=> Fix pre-release/release workflows

src/Giraffe/EndpointRouting.fs
This PR adds the ability to configure endpoints via the IEndpointConventionBuilder. This would enable us to reuse some of the built-in OpenApi generation to generate OpenApi schemas from code. It's possible by replacing the `MetadataList` with a `ConfigureEndpoint`, which can be utilized to capture additional information about the endpoint. 
I've taken inspiration from Oxpeckers [Routing](https://github.com/Lanayx/Oxpecker/blob/develop/src/Oxpecker/Routing.fs) which uses a similar approach.
A working example provided in the [Giraffe.OpenApi](https://github.com/mrtz-j/Giraffe.OpenApi) repo, which utilizes this branch. It's based on the MinimalApi approach, with a more functional syntax. 
```fsharp
|> configureEndpoint _.WithName("Endpoint")
|> withOpenApi<unit, string>
```
In the …
=> Add ability to Configure Endpoints via IEndpointConventionBuilder

RELEASE_NOTES.md
The RELEASE_NOTES document does not mention that the `NewtonsoftJson` and `SystemTextJson` modules were removed by PR https://github.com/giraffe-fsharp/Giraffe/pull/563. I'm adding this information with this PR.
- Related to https://github.com/giraffe-fsharp/Giraffe/issues/606.
=> Update RELEASE_NOTES with removed Json modules information

src/Giraffe/Preconditional.fs
With this PR, I'm solving this scan result (ionide.Analyzers) for the `Preconditional.fs` file, rule id IONIDE-006:
> Replace unsafe option unwrapping with graceful handling of each case.
+ Documentation [link](https://ionide.io/ionide-analyzers/suggestion/006.html#HandleOptionGracefullyAnalyzer).
> [!NOTE]
> This will not change any project behavior.
Solves:
+ https://github.com/giraffe-fsharp/Giraffe/security/code-scanning/15
+ https://github.com/giraffe-fsharp/Giraffe/security/code-scanning/14
=> HandleOptionGracefullyAnalyzer for ETag and Last-Modified at Preconditional.fs 

MAINTAINERS.md, README.md
Listing the new maintainers of Giraffe.
@dustinmoris, would you be okay if I removed the Slack channel section? I have a gut feeling that it is no longer a viable option for discussing Giraffe.
=> Add maintainers info

src/Giraffe/HttpContextExtensions.fs, tests/Giraffe.Tests/Helpers.fs, tests/Giraffe.Tests/HttpContextExtensionsTests.fs
As noticed by @xperiandri, the `ReadBodyFromRequestAsync` seems to be incorrectly disposing the `ctx.Request.Body`. I'm adopting the suggestion from @Banashek, to use the `leaveOpen = true` parameter.
From the [docs](https://learn.microsoft.com/en-us/dotnet/api/system.io.streamreader.-ctor?view=net-8.0#overloads):
> Unless you set the leaveOpen parameter to true, the [StreamReader](https://learn.microsoft.com/en-us/dotnet/api/system.io.streamreader?view=net-8.0) object calls [Dispose()](https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.dispose?view=net-8.0#system-io-stream-dispose) on the provided [Stream](https://learn.microsoft.com/en-us/dotnet/api/system.io.stream?view=net-8.0) object when [StreamReader.Dispose](https://learn.microsoft.com/en-us/dotnet/api/system.io.streamre …
=> Fix `ReadBodyFromRequestAsync` disposing `ctx.Request.Body`

.github/dependabot.yml
With this PR, I'm adding the [GitHub dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file) configuration so we receive alerts whenever new versions are available.
=> Add GitHub dependabot configuration

DEVGUIDE.md, src/Giraffe/Giraffe.fsproj
With this PR, I'm adding the **AssemblyVersion** attribute to Giraffe.fsproj, and updating the DEVGUIDE document, adding a new step to update this attribute whenever a new release is intended.
- Close https://github.com/giraffe-fsharp/Giraffe/issues/521
=> Add AssemblyVersion attribute

README.md
With this PR, I'm adding more links to the README with posts and videos related to F# + Giraffe. 
Most are from Hamilton 🚀.
=> Add more links

.github/dependabot.yml, .github/workflows/build-and-test.yml, .github/workflows/fantomas-check.yml, .github/workflows/publish.yml, src/Giraffe/Giraffe.fsproj, tests/Giraffe.Tests/Giraffe.Tests.fsproj
With this PR, 
- I'm adding .NET 9 as a target framework;
- Changing **fantomas** CI to run using ubuntu-latest;
- Changing **build-and-test** push trigger to execute only for pushes to the `master` branch;
- Update dependabot configuration to scan multiple [directories](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#directories-or-directory--);
- Clean test dependencies and remove .NET 6 and 7 from target frameworks.
Check CI.
=> Add .NET 9 as target framework, fine-tune dependabot, update CI and clean tests removing .NET 6/7 from target frameworks

.github/dependabot.yml
Revert the dependabot setup introduced with PR https://github.com/giraffe-fsharp/Giraffe/pull/639.
Reason: It started creating some duplicated PRs:
=> Revert dependabot configuration to scan only one directory

src/Giraffe/RequestLimitation.fs, src/Giraffe/ResponseCaching.fs, tests/Giraffe.Tests/Giraffe.Tests.fsproj, tests/Giraffe.Tests/ResponseCachingTests.fs
Fix the following code scan warnings:
- Replace unsafe option unwrapping with graceful handling of each case.
- https://github.com/giraffe-fsharp/Giraffe/security/code-scanning/36
- https://github.com/giraffe-fsharp/Giraffe/security/code-scanning/9
- Checks if calls of Seq functions can be replaced with functions from the collection modules
- https://github.com/giraffe-fsharp/Giraffe/security/code-scanning/32
- https://github.com/giraffe-fsharp/Giraffe/security/code-scanning/31
Before this PR (29 open items):
After this PR (25 open items):
Check CI.
=> Code scanning fix patches

DEVGUIDE.md, src/Giraffe/Giraffe.fsproj
With this PR, I'm replacing the `AssemblyVersion` with `Version` metadata from Giraffe.fsproj.
- Build the project locally and inspect the generated `dll`.
- Assert the metadata is correct. For example:
Related to this comment: https://github.com/giraffe-fsharp/Giraffe/pull/629#issuecomment-2799893629.
=> Fix assembly version

DOCUMENTATION.md, samples/EndpointRoutingApp/Program.fs, src/Giraffe/EndpointRouting.fs, tests/Giraffe.Tests/EndpointRoutingTests.fs
Add support for named parameters to `routef`. This allows you to use the syntax `%i:barcode` to name a parameter.
This will allow the Giraffe.OpenApi package to have named parameters instead of their names being simple `[type][index]` (e.g., "i0").
1. Pull down the repo.
2. Run the EndpointRoutingApp sample app.
3. Navigate to `https://localhost:56830/pet/123`.
4. Should see text: "PetId: 123"
https://github.com/giraffe-fsharp/Giraffe/issues/611
=> Enhance routef support for named parameters and improve documentation

DOCUMENTATION.md, tests/Giraffe.Tests/HttpHandlerTests.fs
With this PR, I'm adding more information to the JSON documentation section, and adding new tests to assert that the expected JSON format is being parsed correctly by the default serializer.
- Read the docs;
- Run `dotnet test`, or check CI.
=> Improve JSON docs
